/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pastry_project_orderingsystem;

import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.sql.Statement;
import java.sql.ResultSet;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yvette Rimas
 */
public class Menu extends javax.swing.JFrame {
    
    Color DefaultColor,ClickedColor;
    Connection con;
    PreparedStatement pst;
    Statement st;
    ResultSet rs;
    int lastID;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        DefaultColor = new Color (204,102,0);
        ClickedColor = new Color (255,204,153);
        
        Cakes.setBackground(DefaultColor);
        Rice.setBackground(DefaultColor);
        Pizza.setBackground(DefaultColor);
        Pasta.setBackground(DefaultColor);
        Others.setBackground(DefaultColor);
        Drinks.setBackground(DefaultColor);
        FFS.setBackground(DefaultColor);
        Coffee.setBackground(DefaultColor);
        Yogurt.setBackground(DefaultColor);
        
        Connect();
        OrderNum();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        left = new javax.swing.JPanel();
        items = new javax.swing.JPanel();
        Rice = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Cakes = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Pizza = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Pasta = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Drinks = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Others = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Yogurt = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        FFS = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Coffee = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        right = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        OrderName = new javax.swing.JTextField();
        Quantity = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        Subtotal = new javax.swing.JTextField();
        Clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cart = new javax.swing.JTable();
        OrderNumber = new javax.swing.JLabel();
        Print = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Add2Cart = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        Price = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        PayAmount = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Total = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        Change = new javax.swing.JTextField();
        Pay = new javax.swing.JButton();
        TakeOut = new javax.swing.JButton();
        DineIn = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        Service = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left.setBackground(new java.awt.Color(255, 255, 255));
        left.setPreferredSize(new java.awt.Dimension(500, 750));
        left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        items.setBackground(new java.awt.Color(204, 102, 0));
        items.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Rice.setBackground(new java.awt.Color(204, 102, 0));
        Rice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Rice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RiceMousePressed(evt);
            }
        });
        Rice.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 0));
        jLabel4.setText("              Rice Meals");
        Rice.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, -1));
        jLabel4.getAccessibleContext().setAccessibleName("            Rice Meals");

        items.add(Rice, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 240, 40));

        Cakes.setBackground(new java.awt.Color(204, 102, 0));
        Cakes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cakes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CakesMousePressed(evt);
            }
        });
        Cakes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 51, 0));
        jLabel5.setText("   Cakes and Cheesecakes");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        Cakes.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, -1));

        items.add(Cakes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, 40));

        Pizza.setBackground(new java.awt.Color(204, 102, 0));
        Pizza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PizzaMousePressed(evt);
            }
        });
        Pizza.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 51, 0));
        jLabel6.setText("                  Pizza");
        Pizza.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, -1));

        items.add(Pizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 240, 40));

        Pasta.setBackground(new java.awt.Color(204, 102, 0));
        Pasta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pasta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PastaMousePressed(evt);
            }
        });
        Pasta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 51, 0));
        jLabel7.setText("                 Pasta");
        Pasta.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, -1));

        items.add(Pasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 240, 40));

        Drinks.setBackground(new java.awt.Color(204, 102, 0));
        Drinks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Drinks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DrinksMousePressed(evt);
            }
        });
        Drinks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 51, 0));
        jLabel8.setText("                Drinks");
        Drinks.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, -1));

        items.add(Drinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 240, 40));

        Others.setBackground(new java.awt.Color(204, 102, 0));
        Others.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Others.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OthersMousePressed(evt);
            }
        });
        Others.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 51, 0));
        jLabel9.setText("                Others");
        Others.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, -1));

        items.add(Others, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 240, 40));

        Yogurt.setBackground(new java.awt.Color(204, 102, 0));
        Yogurt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Yogurt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                YogurtMousePressed(evt);
            }
        });
        Yogurt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 51, 0));
        jLabel10.setText("        Yogurt Smoothie");
        Yogurt.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 51, 0));
        jLabel13.setText("          and Fruit Ades");
        Yogurt.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, -1));

        items.add(Yogurt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 240, 50));

        FFS.setBackground(new java.awt.Color(204, 102, 0));
        FFS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FFS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FFSMousePressed(evt);
            }
        });
        FFS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 51, 0));
        jLabel11.setText("       Fresh Fruit Shakes");
        FFS.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, -1));

        items.add(FFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 240, 40));

        Coffee.setBackground(new java.awt.Color(204, 102, 0));
        Coffee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Coffee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CoffeeMousePressed(evt);
            }
        });
        Coffee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 51, 0));
        jLabel12.setText("                Coffee");
        Coffee.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, -1));

        items.add(Coffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 240, 40));

        left.add(items, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 240, 630));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setText("MENU");
        left.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logo 2.png"))); // NOI18N
        left.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/pngtree-vector-house-icon-png-image_695726.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        left.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        left.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 580, 630));

        container.add(left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        right.setBackground(new java.awt.Color(102, 51, 0));
        right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 204, 153));
        jLabel14.setText("Subtotal");
        right.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));
        right.add(OrderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 220, -1));

        Quantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                QuantityStateChanged(evt);
            }
        });
        right.add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 110, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 204, 153));
        jLabel15.setText("Quantity");
        right.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));
        right.add(Subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 80, -1));

        Clear.setText("Clear");
        Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        right.add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 110, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 204, 153));
        jScrollPane1.setBorder(null);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Cart.setBackground(new java.awt.Color(255, 204, 153));
        Cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Price", "Quantity", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Cart);

        right.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 400, 280));

        OrderNumber.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        OrderNumber.setForeground(new java.awt.Color(255, 204, 153));
        OrderNumber.setText("--");
        right.add(OrderNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        Print.setText("Print Receipt");
        Print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        right.add(Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 640, 140, 40));

        Remove.setText("Remove");
        Remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });
        right.add(Remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 110, 30));

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 204, 153));
        jLabel16.setText("Your Order#");
        right.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 204, 153));
        jLabel17.setText("Order name");
        right.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        Add2Cart.setText("Add to Cart");
        Add2Cart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add2Cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add2CartActionPerformed(evt);
            }
        });
        right.add(Add2Cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 110, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 204, 153));
        jLabel18.setText("Price");
        right.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));
        right.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 80, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 204, 153));
        jLabel19.setText("Amount Paid:");
        right.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));
        right.add(PayAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, 110, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 204, 153));
        jLabel20.setText("Total:");
        right.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, -1));
        right.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 110, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 204, 153));
        jLabel21.setText("Change:");
        right.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 570, -1, -1));
        right.add(Change, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 110, -1));

        Pay.setText("Pay");
        Pay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayActionPerformed(evt);
            }
        });
        right.add(Pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 110, -1));

        TakeOut.setText("Take Out");
        TakeOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TakeOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeOutActionPerformed(evt);
            }
        });
        right.add(TakeOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 110, 30));

        DineIn.setText("Dine In");
        DineIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DineIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DineInActionPerformed(evt);
            }
        });
        right.add(DineIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 110, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 204, 153));
        jLabel22.setText("Service:");
        right.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, -1, -1));
        right.add(Service, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 110, -1));

        container.add(right, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 480, 750));

        getContentPane().add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

        public void Connect(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/pastryproject", "root", "");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
        public void OrderNum(){
            try{
                con = DriverManager.getConnection("jdbc:mysql://localhost/pastryproject", "root", "");
                String sql = "SELECT MAX(OrderID) FROM pastryproject";
                st = con.createStatement();
                rs = st.executeQuery(sql);
                if(rs.next()){
                    lastID = rs.getInt(1);
                    lastID++;
                    OrderNumber.setText(Integer.toString(lastID));
                }
                
            }
            catch (Exception ex){
                JOptionPane.showMessageDialog(this, ex);
            }
        }
//        public void OrderNum(){
//        try{
//            Statement st = con.createStatement();
//            ResultSet rs = st.executeQuery("SELECT MAX(OrderID) FROM pastryproject");
//            rs.next();
//            
//            rs.getString("MAX(OrderID)");
//            
//            if(rs.getString("MAX(OrderID)") == null){
//                OrderNumber.setText("001");
//            }else{
//                long id = Long.parseLong(rs.getString("MAX(OrderID)").substring(2, rs.getString("MAX(OrderID)").length()));
//                id++;
//                OrderNumber.setText(String.format("%02d", id));
//            }
//            
//        } catch (SQLException ex) {
//            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
            
         public void Database(){
        
        try {
            String num = OrderNumber.getText();
            String serv = Service.getText();
            String total = Total.getText();
            String amnt = PayAmount.getText();
            String chng = Change.getText();
            
            pst = con.prepareStatement("INSERT INTO pastryproject(OrderID, Service, Total, AmountPaid, ChangeAmount)values(?,?,?,?,?)");
            
            pst.setString(1, num);
            pst.setString(2, serv);
            pst.setString(3, total);
            pst.setString(4, amnt);
            pst.setString(5, chng);
            pst.executeUpdate();
            OrderNum();
            
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
        
    public void Change() {
        double total = Double.parseDouble(Total.getText());
        double pay = Double.parseDouble(PayAmount.getText());
        
        double chng = pay - total;
        
        Change.setText(String.valueOf(chng));
    }
    
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Homepage home = new Homepage();
        home.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void CakesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CakesMousePressed
        Cakes.setBackground(ClickedColor);
        Rice.setBackground(DefaultColor);
        Pizza.setBackground(DefaultColor);
        Pasta.setBackground(DefaultColor);
        Others.setBackground(DefaultColor);
        Drinks.setBackground(DefaultColor);
        FFS.setBackground(DefaultColor);
        Coffee.setBackground(DefaultColor);
        Yogurt.setBackground(DefaultColor);
    }//GEN-LAST:event_CakesMousePressed

    private void PizzaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PizzaMousePressed
        Cakes.setBackground(DefaultColor);
        Rice.setBackground(DefaultColor);
        Pizza.setBackground(ClickedColor);
        Pasta.setBackground(DefaultColor);
        Others.setBackground(DefaultColor);
        Drinks.setBackground(DefaultColor);
        FFS.setBackground(DefaultColor);
        Coffee.setBackground(DefaultColor);
        Yogurt.setBackground(DefaultColor);
    }//GEN-LAST:event_PizzaMousePressed

    private void RiceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RiceMousePressed
        Cakes.setBackground(DefaultColor);
        Rice.setBackground(ClickedColor);
        Pizza.setBackground(DefaultColor);
        Pasta.setBackground(DefaultColor);
        Others.setBackground(DefaultColor);
        Drinks.setBackground(DefaultColor);
        FFS.setBackground(DefaultColor);
        Coffee.setBackground(DefaultColor);
        Yogurt.setBackground(DefaultColor);
    }//GEN-LAST:event_RiceMousePressed

    private void PastaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PastaMousePressed
        Cakes.setBackground(DefaultColor);
        Rice.setBackground(DefaultColor);
        Pizza.setBackground(DefaultColor);
        Pasta.setBackground(ClickedColor);
        Others.setBackground(DefaultColor);
        Drinks.setBackground(DefaultColor);
        FFS.setBackground(DefaultColor);
        Coffee.setBackground(DefaultColor);
        Yogurt.setBackground(DefaultColor);
    }//GEN-LAST:event_PastaMousePressed

    private void OthersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OthersMousePressed
        Cakes.setBackground(DefaultColor);
        Rice.setBackground(DefaultColor);
        Pizza.setBackground(DefaultColor);
        Pasta.setBackground(DefaultColor);
        Others.setBackground(ClickedColor);
        Drinks.setBackground(DefaultColor);
        FFS.setBackground(DefaultColor);
        Coffee.setBackground(DefaultColor);
        Yogurt.setBackground(DefaultColor);
    }//GEN-LAST:event_OthersMousePressed

    private void DrinksMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrinksMousePressed
        Cakes.setBackground(DefaultColor);
        Rice.setBackground(DefaultColor);
        Pizza.setBackground(DefaultColor);
        Pasta.setBackground(DefaultColor);
        Others.setBackground(DefaultColor);
        Drinks.setBackground(ClickedColor);
        FFS.setBackground(DefaultColor);
        Coffee.setBackground(DefaultColor);
        Yogurt.setBackground(DefaultColor);
    }//GEN-LAST:event_DrinksMousePressed

    private void FFSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FFSMousePressed
        Cakes.setBackground(DefaultColor);
        Rice.setBackground(DefaultColor);
        Pizza.setBackground(DefaultColor);
        Pasta.setBackground(DefaultColor);
        Others.setBackground(DefaultColor);
        Drinks.setBackground(DefaultColor);
        FFS.setBackground(ClickedColor);
        Coffee.setBackground(DefaultColor);
        Yogurt.setBackground(DefaultColor);
    }//GEN-LAST:event_FFSMousePressed

    private void CoffeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CoffeeMousePressed
        Cakes.setBackground(DefaultColor);
        Rice.setBackground(DefaultColor);
        Pizza.setBackground(DefaultColor);
        Pasta.setBackground(DefaultColor);
        Others.setBackground(DefaultColor);
        Drinks.setBackground(DefaultColor);
        FFS.setBackground(DefaultColor);
        Coffee.setBackground(ClickedColor);
        Yogurt.setBackground(DefaultColor);
    }//GEN-LAST:event_CoffeeMousePressed

    private void YogurtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YogurtMousePressed
        Cakes.setBackground(DefaultColor);
        Rice.setBackground(DefaultColor);
        Pizza.setBackground(DefaultColor);
        Pasta.setBackground(DefaultColor);
        Others.setBackground(DefaultColor);
        Drinks.setBackground(DefaultColor);
        FFS.setBackground(DefaultColor);
        Coffee.setBackground(DefaultColor);
        Yogurt.setBackground(ClickedColor);
    }//GEN-LAST:event_YogurtMousePressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        CakesItems cakes = new CakesItems();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(cakes).setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void QuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_QuantityStateChanged
        int qty = Integer.parseInt(Quantity.getValue().toString());
        if (qty < 0){
           Quantity.setValue(0);
        }else {
            double price = Double.parseDouble(Price.getText());
            Subtotal.setText(String.valueOf(qty * price));
        }
    }//GEN-LAST:event_QuantityStateChanged

    private void Add2CartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add2CartActionPerformed
        DefaultTableModel model = new DefaultTableModel();
        
        model = (DefaultTableModel)Cart.getModel();
        model.addRow(new Object[]{
            
            OrderName.getText(), Price.getText(), Quantity.getValue().toString(), Subtotal.getText()
        });
        
        double sum = 0;
        
        for (int i = 0; i < Cart.getRowCount(); i++){
            sum = sum + Double.parseDouble(Cart.getValueAt(i, 3).toString());
        }
        
        Total.setText(Double.toString(sum));
    }//GEN-LAST:event_Add2CartActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        OrderName.setText("");
        Price.setText("");
        Subtotal.setText("");
        Quantity.setValue(0);
    }//GEN-LAST:event_ClearActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        DefaultTableModel model = new DefaultTableModel();
        
        model = (DefaultTableModel)Cart.getModel();
        model.removeRow(Cart.getSelectedRow());
        
        double sum = 0;
        for (int i = 0; i < Cart.getRowCount(); i++){
            sum = sum + Double.parseDouble(Cart.getValueAt(i, 3).toString());
        }
        
        Total.setText(Double.toString(sum));
    }//GEN-LAST:event_RemoveActionPerformed

    private void DineInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DineInActionPerformed
        String service = "Dine In";
        
        Service.setText(service);
    }//GEN-LAST:event_DineInActionPerformed

    private void TakeOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeOutActionPerformed
        String service = "Take Out";
        
        Service.setText(service);
    }//GEN-LAST:event_TakeOutActionPerformed

    private void PayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayActionPerformed
        Change();
        
        String num = OrderNumber.getText();
        String serv = Service.getText();
        String total = Total.getText();
        String amnt = PayAmount.getText();
    }//GEN-LAST:event_PayActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        String todaydate = dFormat.format(date);
        String total = String.valueOf(Total);
        
        
        String path = "F:\\";
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try{
            PdfWriter.getInstance(doc, new FileOutputStream(path + "Order Receipt " + OrderNumber.getText() + ".pdf"));
            doc.open();
            Paragraph pastryName = new Paragraph("                                                               PASTRY PROJECT\n");
            doc.add(pastryName);
            Paragraph bakeshop = new Paragraph("                                                                 Bakeshop & Cafe\n");
            doc.add(bakeshop);
            Paragraph contact = new Paragraph("                                                        Contact No. 0938-796-2033\n");
            doc.add(contact);
            Paragraph dadate = new Paragraph("                                                      " + date);
            doc.add(dadate);
            Paragraph line = new Paragraph("----------------------------------------------------------------------------------------------------------------------------------\n");
            doc.add(line);
            Paragraph service = new Paragraph("                                                                         " + Service.getText() + "\n");
            doc.add(service);
            Paragraph ordernum = new Paragraph("                                                                     Order# " + OrderNumber.getText() + "\n");
            doc.add(ordernum);
            Paragraph space = new Paragraph("                                                                                                                               ");
            doc.add(space);
            PdfPTable tbl = new PdfPTable(4);
            tbl.addCell("Item");
            tbl.addCell("Price");
            tbl.addCell("Quantity");
            tbl.addCell("Subtotal");
            for (int i = 0; i < Cart.getRowCount(); i++){
                String n = Cart.getValueAt(i, 0).toString();
                String d = Cart.getValueAt(i, 1).toString();
                String r = Cart.getValueAt(i, 2).toString();
                String q = Cart.getValueAt(i, 3).toString();
                
                tbl.addCell(n);
                tbl.addCell(d);
                tbl.addCell(r);
                tbl.addCell(q);
            }
            doc.add(tbl);
            doc.add(line);
            Paragraph orderTotal = new Paragraph("                                                                                                     Total: " + Total.getText() + "\n");
            doc.add(orderTotal);
            Paragraph orderPay = new Paragraph("                                                                                          Amount Paid: " + PayAmount.getText() + "\n");
            doc.add(orderPay);
            Paragraph orderChange = new Paragraph("                                                                                               Change: " + Change.getText() + "\n");
            doc.add(orderChange);
            doc.add(line);
            Paragraph msg = new Paragraph("                                                          Thank You for Your Order!\n");
            doc.add(msg);
            Paragraph updated = new Paragraph("                                                                    Stay Updated @\n");
            doc.add(updated);
            Paragraph fbpage = new Paragraph("                                                        facebook.com/pastryproject.bc\n");
            doc.add(fbpage);
            Paragraph insta = new Paragraph("                                                        instagram.com/pastryproject.bc\n");
            doc.add(insta);
            
        }catch(DocumentException | FileNotFoundException e){
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();
        setVisible(false);
        
        Database();                      
    }//GEN-LAST:event_PrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add2Cart;
    private javax.swing.JPanel Cakes;
    private javax.swing.JTable Cart;
    private javax.swing.JTextField Change;
    private javax.swing.JButton Clear;
    private javax.swing.JPanel Coffee;
    private javax.swing.JButton DineIn;
    private javax.swing.JPanel Drinks;
    private javax.swing.JPanel FFS;
    public static javax.swing.JTextField OrderName;
    private javax.swing.JLabel OrderNumber;
    private javax.swing.JPanel Others;
    private javax.swing.JPanel Pasta;
    private javax.swing.JButton Pay;
    private javax.swing.JTextField PayAmount;
    private javax.swing.JPanel Pizza;
    public static javax.swing.JTextField Price;
    private javax.swing.JButton Print;
    private javax.swing.JSpinner Quantity;
    private javax.swing.JButton Remove;
    private javax.swing.JPanel Rice;
    private javax.swing.JTextField Service;
    private javax.swing.JTextField Subtotal;
    private javax.swing.JButton TakeOut;
    private javax.swing.JTextField Total;
    private javax.swing.JPanel Yogurt;
    public javax.swing.JPanel container;
    private javax.swing.JPanel items;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel left;
    private javax.swing.JPanel right;
    // End of variables declaration//GEN-END:variables
}
